def my_cad_function(args):
    import cadquery as cq
    import os
    import math

    source = cq.importers.importStep(os.path.expanduser(args['input_file']))
    src = source.val()
    bb = src.BoundingBox()
    print('SOURCE_VALID', src.isValid())
    print('SOURCE_BBOX', bb.xmin, bb.xmax, bb.ymin, bb.ymax, bb.zmin, bb.zmax)

    x0, x1 = bb.xmin, bb.xmax
    y0, y1 = bb.ymin, bb.ymax
    z0, z1 = bb.zmin, bb.zmax

    junction_x = 100.0
    spine_y0 = 230.0
    spine_y1 = 295.0
    spine_z0 = -445.0
    spine_mid_y = 0.5 * (spine_y0 + spine_y1)

    # Reconstruct the unfilleted parent geometry. The nose and spine use one
    # continuous side plane, eliminating the former one-sided external step.
    # Rebuilding the parent also removes every legacy chamfer and external round.
    housing = (
        cq.Workplane('XY', origin=(x0, y0, z0))
        .box(junction_x - x0, y1 - y0, z1 - z0,
             centered=(False, False, False))
    )
    spine = (
        cq.Workplane('XY', origin=(junction_x, spine_y0, spine_z0))
        .box(x1 - junction_x, spine_y1 - spine_y0, z1 - spine_z0,
             centered=(False, False, False))
    )
    solid = housing.union(spine).combine().clean().val()
    print('SHARP_PARENT_VALID', solid.isValid(), 'FACES', len(solid.Faces()))

    def is_line(edge):
        try:
            return edge.geomType() == 'LINE'
        except Exception:
            return False

    def edge_axis(edge):
        eb = edge.BoundingBox()
        dims = (eb.xlen, eb.ylen, eb.zlen)
        return max(range(3), key=lambda i: dims[i])

    def adjacent_faces(shape, edge):
        result = []
        for face in shape.Faces():
            for fe in face.Edges():
                try:
                    same = edge.isSame(fe)
                except Exception:
                    same = edge.hashCode() == fe.hashCode()
                if same:
                    result.append(face)
                    break
        return result

    def is_sharp(shape, edge):
        # Do not select the straight tangent boundaries generated by R20/R5.
        faces = adjacent_faces(shape, edge)
        if len(faces) != 2:
            return False
        c = edge.Center()
        try:
            n1 = faces[0].normalAt(c)
            n2 = faces[1].normalAt(c)
            l1 = math.sqrt(n1.x*n1.x + n1.y*n1.y + n1.z*n1.z)
            l2 = math.sqrt(n2.x*n2.x + n2.y*n2.y + n2.z*n2.z)
            if l1 < 1e-9 or l2 < 1e-9:
                return True
            dot = abs((n1.x*n2.x + n1.y*n2.y + n1.z*n2.z)/(l1*l2))
            return dot < 0.985
        except Exception:
            return True

    def sharp_lines(shape):
        return [e for e in shape.Edges() if is_line(e) and is_sharp(shape, e)]

    # R20 is assigned only to the two transverse horizontal shoulder edges at
    # the top of the narrow-to-large transition.
    r20_edges = []
    for edge in solid.Edges():
        if not is_line(edge):
            continue
        c = edge.Center()
        eb = edge.BoundingBox()
        transverse = eb.ylen > 1.0 and eb.xlen < 1e-5 and eb.zlen < 1e-5
        if (transverse and abs(c.x - junction_x) < 1e-4 and
                abs(c.z - z1) < 1e-4):
            r20_edges.append(edge)

    print('R20_CANDIDATES', len(r20_edges))
    if r20_edges:
        try:
            trial = cq.Workplane(obj=solid).newObject(r20_edges).fillet(20.0).val()
            if not trial.isValid():
                raise RuntimeError('invalid R20 result')
            solid = trial.clean()
            print('R20_SUCCEEDED', len(r20_edges))
        except Exception as exc:
            print('R20_FAILED', str(exc)[:200])

    def apply_r5_group(name, predicate):
        nonlocal solid
        targets = [e for e in sharp_lines(solid) if predicate(e)]
        print('R5_GROUP_CANDIDATES', name, len(targets))
        if not targets:
            return

        try:
            trial = cq.Workplane(obj=solid).newObject(targets).fillet(5.0).val()
            if not trial.isValid():
                raise RuntimeError('invalid grouped result')
            solid = trial.clean()
            print('R5_GROUP_SUCCEEDED', name, len(targets))
            return
        except Exception as exc:
            print('R5_GROUP_COMBINED_FAILED', name, str(exc)[:160])

        # Retry coherent parallel subsets before falling back to individual
        # edges. This is more reliable at mixed R20/R5 vertices.
        for axis in (0, 1, 2):
            subset = [e for e in sharp_lines(solid)
                      if predicate(e) and edge_axis(e) == axis]
            if not subset:
                continue
            try:
                trial = cq.Workplane(obj=solid).newObject(subset).fillet(5.0).val()
                if trial.isValid():
                    solid = trial.clean()
                    print('R5_SUBGROUP_SUCCEEDED', name, axis, len(subset))
                    continue
            except Exception as exc:
                print('R5_SUBGROUP_FAILED', name, axis, str(exc)[:120])

            # Last-resort greedy processing records genuine geometric conflicts
            # rather than silently changing the requested radius.
            conflicts = 0
            keys = []
            for e in subset:
                c = e.Center()
                keys.append((c.x, c.y, c.z, e.Length(), axis))
            for key in keys:
                candidates = [e for e in sharp_lines(solid)
                              if predicate(e) and edge_axis(e) == key[4]]
                if not candidates:
                    continue
                edge = min(candidates, key=lambda e:
                    (e.Center().x-key[0])**2 +
                    (e.Center().y-key[1])**2 +
                    (e.Center().z-key[2])**2 +
                    0.0025*(e.Length()-key[3])**2)
                try:
                    trial = cq.Workplane(obj=solid).newObject([edge]).fillet(5.0).val()
                    if trial.isValid():
                        solid = trial.clean()
                    else:
                        conflicts += 1
                except Exception:
                    conflicts += 1
            if conflicts:
                print('R5_GEOMETRIC_CONFLICTS', name, axis, conflicts)

    # Longitudinal outer corners are processed first. This was the missing edge
    # class in the preceding result and removes the visibly sharp long edges.
    apply_r5_group('longitudinal', lambda e: edge_axis(e) == 0)

    # Round the complete front and rear end perimeters after the longitudinal
    # rounds so their vertices resolve as rolling-ball corners.
    apply_r5_group('front', lambda e: abs(e.Center().x - x1) < 0.2)
    apply_r5_group('rear', lambda e: abs(e.Center().x - x0) < 0.2)

    # Treat every remaining sharp external edge, including non-horizontal
    # shoulder edges. Tangent boundaries of the R20 faces are excluded by the
    # dihedral-angle test.
    apply_r5_group('remaining_external', lambda e: True)

    # Restore the functional blind axial socket without changing its straight
    # cylindrical diameter or axis away from the entrance/end blends.
    socket_z = -400.0
    socket_radius = 20.0
    socket_closed_x = junction_x
    socket_tool = cq.Solid.makeCylinder(
        socket_radius,
        x1 - socket_closed_x,
        cq.Vector(x1, spine_mid_y, socket_z),
        cq.Vector(-1, 0, 0)
    )
    solid = solid.cut(socket_tool).clean()

    socket_edges = []
    for edge in solid.Edges():
        try:
            if edge.geomType() not in ('CIRCLE', 'ELLIPSE'):
                continue
        except Exception:
            continue
        c = edge.Center()
        eb = edge.BoundingBox()
        centered = (abs(c.y-spine_mid_y) < 0.15 and
                    abs(c.z-socket_z) < 0.15)
        correct_size = eb.ylen > 39.0 and eb.zlen > 39.0
        at_end = (abs(c.x-x1) < 0.15 or
                  abs(c.x-socket_closed_x) < 0.15)
        if centered and correct_size and at_end:
            socket_edges.append(edge)

    print('SOCKET_R5_CANDIDATES', len(socket_edges))
    if socket_edges:
        try:
            trial = cq.Workplane(obj=solid).newObject(socket_edges).fillet(5.0).val()
            if not trial.isValid():
                raise RuntimeError('invalid socket fillet result')
            solid = trial.clean()
            print('SOCKET_R5_SUCCEEDED', len(socket_edges))
        except Exception as exc:
            print('SOCKET_R5_FAILED', str(exc)[:200])

    # Preserve the intentional one-sided latch pocket. A fully R5-rounded cutter
    # gives all pocket opening and internal corner edges the replacement radius.
    pocket_tool = (
        cq.Workplane('XY', origin=(125.0, 220.0, -407.5))
        .box(45.0, 62.0, 35.0, centered=(False, False, False))
    )
    try:
        pocket_tool = pocket_tool.edges().fillet(5.0)
        print('POCKET_R5_TOOL_SUCCEEDED')
    except Exception as exc:
        print('POCKET_R5_TOOL_FAILED', str(exc)[:200])
    solid = solid.cut(pocket_tool.val()).clean()

    remaining_sharp = sharp_lines(solid)
    print('FINAL_SHARP_LINE_COUNT', len(remaining_sharp))
    for i, edge in enumerate(remaining_sharp[:20]):
        c = edge.Center()
        print('FINAL_SHARP_EDGE', i, round(c.x, 3), round(c.y, 3),
              round(c.z, 3), round(edge.Length(), 3), edge_axis(edge))

    out_bb = solid.BoundingBox()
    print('RESULT_VALID', solid.isValid())
    print('RESULT_VOLUME', round(solid.Volume(), 3))
    print('RESULT_BBOX', round(out_bb.xmin, 3), round(out_bb.xmax, 3),
          round(out_bb.ymin, 3), round(out_bb.ymax, 3),
          round(out_bb.zmin, 3), round(out_bb.zmax, 3))
    print('RESULT_COUNTS', len(solid.Faces()), len(solid.Edges()),
          len(solid.Vertices()))
    return cq.Workplane(obj=solid)
