def my_cad_function(args):
    import os
    import cadquery as cq

    input_file = os.path.expanduser(args['input_file'])
    source = cq.importers.importStep(input_file)
    source_shape = source.val() if hasattr(source, 'val') else source
    print('SOURCE VALID:', source_shape.isValid())
    print('SOURCE VOLUME:', source_shape.Volume())

    tol = 1.0e-4

    def as_single_solid(shape):
        if hasattr(shape, 'Solids'):
            solids = shape.Solids()
            if len(solids) == 1:
                return solids[0]
        return shape

    def fillet_edges(shape, edges, radius):
        if not edges:
            return shape
        wp = cq.Workplane(obj=shape)
        result_wp = wp.newObject(list(edges)).fillet(float(radius)).clean()
        result = as_single_solid(result_wp.val())
        if not result.isValid():
            raise RuntimeError('Invalid fillet result for R{}'.format(radius))
        return result

    def tangent_axis(edge):
        try:
            tangent = edge.tangentAt(0.5)
            components = [abs(tangent.x), abs(tangent.y), abs(tangent.z)]
            return components.index(max(components))
        except Exception:
            return -1

    def close_to_any(value, levels):
        return any(abs(value - level) < tol for level in levels)

    # Reconstruct the design prisms without any of the original chamfers or
    # fillets. Both sections now occupy z=-450 to z=-340, eliminating the
    # one-sided thickness step and making the part symmetric in thickness.
    head = cq.Solid.makeBox(
        100.0, 120.0, 110.0,
        cq.Vector(0.0, 200.0, -450.0)
    )
    arm = cq.Solid.makeBox(
        200.0, 64.336015, 110.0,
        cq.Vector(100.0, 230.0, -450.0)
    )

    base = as_single_solid(cq.Workplane(obj=head).union(arm).clean().val())
    print('SHARP SYMMETRIC BASE VALID:', base.isValid())
    print('SHARP SYMMETRIC BASE EDGES:', len(base.Edges()))

    # The four exposed Y-directed edges at the narrow/wide junction are the
    # horizontal junction edges when viewed from the axial/front direction.
    # Apply the exceptional R20 rule before applying R5 elsewhere.
    shoulder_edges = []
    for edge in base.Edges():
        if edge.geomType() != 'LINE' or tangent_axis(edge) != 1:
            continue
        c = edge.Center()
        bb = edge.BoundingBox()
        if abs(c.x - 100.0) > tol:
            continue
        if not (abs(c.z + 450.0) < tol or abs(c.z + 340.0) < tol):
            continue
        if bb.ymax <= 230.0 + tol or bb.ymin >= 294.336015 - tol:
            shoulder_edges.append(edge)

    print('R20 JUNCTION EDGES:', len(shoulder_edges))
    try:
        outer = fillet_edges(base, shoulder_edges, 20.0)
        print('R20 JUNCTION FILLETS SUCCEEDED')
    except Exception as exc:
        print('GROUPED R20 FAILED:', exc)
        outer = base
        for attempt in range(4):
            candidates = []
            for edge in outer.Edges():
                if edge.geomType() != 'LINE' or tangent_axis(edge) != 1:
                    continue
                c = edge.Center()
                bb = edge.BoundingBox()
                if abs(c.x - 100.0) < tol and (
                    abs(c.z + 450.0) < tol or abs(c.z + 340.0) < tol
                ) and (bb.ymax <= 230.0 + tol or bb.ymin >= 294.336015 - tol):
                    candidates.append(edge)
            if not candidates:
                break
            try:
                outer = fillet_edges(outer, [candidates[0]], 20.0)
            except Exception as edge_exc:
                print('INDIVIDUAL R20 FAILED:', edge_exc)
                break

    # Select only surviving edges belonging to the original sharp prismatic
    # envelope. This avoids applying R5 to tangent boundaries generated by R20.
    x_levels = [0.0, 100.0, 300.0]
    y_levels = [200.0, 230.0, 294.336015, 320.0]
    z_levels = [-450.0, -340.0]

    def remaining_original_edges(shape):
        selected = []
        for edge in shape.Edges():
            if edge.geomType() != 'LINE':
                continue
            bb = edge.BoundingBox()
            axis = tangent_axis(edge)
            if axis == 0:
                matches = (
                    close_to_any(bb.ymin, y_levels) and
                    close_to_any(bb.ymax, y_levels) and
                    close_to_any(bb.zmin, z_levels) and
                    close_to_any(bb.zmax, z_levels)
                )
            elif axis == 1:
                matches = (
                    close_to_any(bb.xmin, x_levels) and
                    close_to_any(bb.xmax, x_levels) and
                    close_to_any(bb.zmin, z_levels) and
                    close_to_any(bb.zmax, z_levels)
                )
            elif axis == 2:
                matches = (
                    close_to_any(bb.xmin, x_levels) and
                    close_to_any(bb.xmax, x_levels) and
                    close_to_any(bb.ymin, y_levels) and
                    close_to_any(bb.ymax, y_levels)
                )
            else:
                matches = False
            if matches:
                selected.append(edge)
        return selected

    r5_edges = remaining_original_edges(outer)
    print('EXTERIOR R5 EDGES:', len(r5_edges))
    try:
        outer = fillet_edges(outer, r5_edges, 5.0)
        print('GROUPED EXTERIOR R5 FILLETS SUCCEEDED')
    except Exception as exc:
        print('GROUPED EXTERIOR R5 FAILED:', exc)
        for attempt in range(40):
            candidates = remaining_original_edges(outer)
            if not candidates:
                break
            candidates.sort(key=lambda edge: edge.Length(), reverse=True)
            succeeded = False
            for edge in candidates:
                try:
                    outer = fillet_edges(outer, [edge], 5.0)
                    succeeded = True
                    break
                except Exception:
                    pass
            if not succeeded:
                print('NO FURTHER EXTERIOR R5 EDGE COULD BE FILLETTED')
                break

    # Create the axial blind bore with R5 built directly into both the blind
    # bottom and the mouth. The mouth flares from radius 20 to radius 25 over
    # the final 5 mm, producing a robust concave R5 after subtraction without
    # relying on the failed post-boolean circular-edge fillet.
    bore_plane = cq.Plane(
        origin=(0.0, 270.0, -400.0),
        xDir=(1.0, 0.0, 0.0),
        normal=(0.0, 0.0, 1.0)
    )
    bore_wp = (
        cq.Workplane(bore_plane)
        .moveTo(100.0, 0.0)
        .lineTo(100.0, 15.0)
        .threePointArc((101.464466, 18.535534), (105.0, 20.0))
        .lineTo(295.0, 20.0)
        .threePointArc((298.535534, 21.464466), (300.0, 25.0))
        .lineTo(305.0, 25.0)
        .lineTo(305.0, 0.0)
        .close()
        .revolve(360.0, (0.0, 0.0), (1.0, 0.0))
    )
    bore = as_single_solid(bore_wp.val())
    print('ROUNDED BORE CUTTER VALID:', bore.isValid())
    result = as_single_solid(outer.cut(bore))

    # Preserve the rectangular side engagement pocket while replacing all of
    # its former chamfers/radii with uniform R5 transitions. The cutter starts
    # outside the -Y wall so its rounded leading edges form R5 mouth radii.
    pocket = cq.Solid.makeBox(
        42.985413, 55.0, 30.949498,
        cq.Vector(125.350920, 225.0, -405.071245)
    )
    try:
        pocket = fillet_edges(pocket, pocket.Edges(), 5.0)
        print('ROUNDED POCKET CUTTER R5 SUCCEEDED')
    except Exception as exc:
        print('GROUPED POCKET R5 FAILED:', exc)
        for attempt in range(20):
            linear_edges = [e for e in pocket.Edges() if e.geomType() == 'LINE']
            if not linear_edges:
                break
            succeeded = False
            for edge in linear_edges:
                try:
                    pocket = fillet_edges(pocket, [edge], 5.0)
                    succeeded = True
                    break
                except Exception:
                    pass
            if not succeeded:
                break

    result = as_single_solid(result.cut(pocket))
    result = as_single_solid(cq.Workplane(obj=result).clean().val())

    print('RESULT VALID:', result.isValid())
    print('RESULT VOLUME:', result.Volume())
    bb = result.BoundingBox()
    print('RESULT BBOX:', (bb.xmin, bb.ymin, bb.zmin), (bb.xmax, bb.ymax, bb.zmax))
    print('RESULT FACES/EDGES:', len(result.Faces()), len(result.Edges()))

    return cq.Workplane(obj=result)
